[general]
live_config_reload = true

# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff8d94'
green = '#c7fb6d'
yellow = '#ffd8ab'
blue = '#9ab8ff'
magenta = '#caabff'
cyan = '#b2ebff'
white = '#c8d3f5'

[font]
size = 16
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[cursor]
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "none"
title = "Alacritty"
padding = { x = 0, y = 0 }
opacity = 1.0
blur = true


[keyboard]
bindings = [
  { chars = "\u001Bh", key = "H", mods = "Command" },
  { chars = "\u001Bl", key = "L", mods = "Command" },
  { chars = "\u001Bw", key = "W", mods = "Command" },
  { chars = "\u001Bc", key = "C", mods = "Command" },
  { chars = "\u001Br", key = "R", mods = "Command" },
  { chars = "\u001Bm", key = "M", mods = "Command" },
  { chars = "\u001By", key = "Y", mods = "Command" },
  { chars = "\u001Bd", key = "D", mods = "Command" },
  { chars = "\u001Bj", key = "J", mods = "Command" },
  { chars = "\u001Bk", key = "K", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },
]
